# fly.toml app configuration file generated for python-portfolio on 2025-03-07T17:24:59-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# fly.toml app configuration file for python-portfolio

app = 'python-portfolio'
primary_region = 'sjc'

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  internal_port = 8081
  protocol = "tcp"

[[services.ports]]
  handlers = ["http"]
  port = 80

[[services.ports]]
  handlers = ["tls"]
  port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

